In [34]:
import numpy as np

# Reshaping Numpy Arrays
#### 1)Ravel
#### 2)Reshape
#### 3)Transpose
#### 4)Stacking
#### 5)Slipting

# 1) Ravel is a function which converts the high dimension arrays such as (2D,3D,4D,100D) into 1D array.

In [35]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr1.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### So, as you can see that in line number 6 arr1 is in 2D while in line number 7 the arr1 is in 1D.

# 1) Reshape, If a number have factor then it will works.

In [37]:
arr2 = np.arange(24)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
arr2.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
arr2.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

# 3) Transpose, Row into column and Column into rows.

In [40]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr3.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

# 4) Stacking is a track through which we can merge two arrays.
### Note: Remeber both arrays have the same number of columns and rows.

In [44]:
arr4 = np.array([[8,9,10],[11,12,13]])

In [45]:
arr5 = np.arange(14,20).reshape(2,3)

In [46]:
np.hstack((arr4,arr5))

array([[ 8,  9, 10, 14, 15, 16],
       [11, 12, 13, 17, 18, 19]])

### The above hstack combine the array horizontaly.However vstack combine the array vertically.

In [47]:
np.vstack((arr4,arr5))

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

# 5) Spliting is use for to separate the array

In [49]:
np.vsplit(arr5,2)

[array([[14, 15, 16]]), array([[17, 18, 19]])]